### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#1]
Should we work in branches and then try to merge for each HW?  I think there could be some problems with that, but it would give everyone a chance to try to do the work and actually keep their stuff in version control.  

The big problem I see is that the repo is monolithic with all of the HW assignments in one so I would think we'd have to make sure to keep our respective branches consistent with the master branch on the older assignments.

**Comment by aisobran** [comment]
The only way I see that working is if we each work on an individual HW assignment. We should avoid for now until we start running into problems with committing.

**Comment by meneal** [comment]
Sounds good to me.  I just thought I'd mention it as an option.

On Wed, Aug 26, 2015 at 10:35 AM, Alexander Sobran <notifications@github.com

**Comment by ghost** [comment]
Yes, I'm fine with putting this off for now unless we run into issues.
