### ISSUE TITLE
Reading 5 Selection

### ISSUE THREAD

**Issue by ghost** [LambdaConglomerate/x9115lam#14]
Looking at [Dr. Menzies' notes](https://github.com/txt/mase/blob/master/READING.md), it looks like we need to summarize one more paper from 2008-2010. A quick search revealed [this one](http://dl.acm.org/citation.cfm?id=1368160) was cited by our Vista paper and is from 2008. What do you all think? Do you have any better suggestions?

**Comment by meneal** [comment]
I think this paper is a fine choice.  It'll be interesting to see what Microsoft Reasearch thinks about the Mythical Man Month.  What do you think, Sasha?

**Comment by aisobran** [comment]
Yeah this paper works for me.

**Comment by aisobran** [comment]
direct link: http://research.microsoft.com/pubs/70535/tr-2008-11.pdf

**Comment by ghost** [comment]
Just pushed a start to the summary. Just be aware, there are quite a few instances of bad grammar in the paper.

**Comment by meneal** [comment]
I just added a bunch of stuff up here.  We just need one more keyword and the connection to other papers and we're all set.  Agreed that there are a ton of mistakes in this paper, I circled 5 or 6.

**Comment by ghost** [comment]
Does anyone else plan on adding the remaining stuff? If not, I'll get this finished by tonight.

**Comment by aisobran** [comment]
I can finish it up

**Comment by aisobran** [comment]
Why are references 1 and 3 in the summary?

**Comment by ghost** [comment]
They were in the previous paper but I didn't remove them in case we wanted to reference them. You can remove them if you don't need them.

**Comment by aisobran** [comment]
Done, I'm good to go on submission.

**Comment by ghost** [comment]
We need two more possible improvements. I can look at the paper again and find them but I'm not sure if any of you had some first.

**Comment by aisobran** [comment]
The earliest I could get to this is by tonight.

**Comment by meneal** [comment]
FYI on upgrade to El Capitan there are problems with Latex.  I stupidly
upgraded thinking that Apple wouldn't screw me again.  They always screw
you.  Whenever you upgrade to El Cap you'll need to download maxtex-2015.
I tried to just fix it in place with my old version, but no dice.
 #applehurtsyousomteimes

**Comment by aisobran** [comment]
I'm on El Capitan. Latex is working fine. Try TexShop.

**Comment by meneal** [comment]
Weird.  I use textmaker.  I don't get anything back when I run `which pdflatex` now.  Did you already install the 2015 version of mactex?  It was already patched.

**Comment by aisobran** [comment]
Not using mactex, I'm using texshop.

**Comment by meneal** [comment]
Texshop is actually mactex/texlive underneath.  Mactex is the one that actually puts out the compiler for OSX.  They have those goofy alice in wonderland graphics on their site, and a huge distribution for OSX at 2.4G.  You can get a smaller version (basictex), but it is short on most of what you need.  

Anyway, good reason to try out one of these fancy latex online editors.  Papeeria seems interesting.

**Comment by meneal** [comment]
I spent some time trying to come up with some other potential improvements, but I honestly can't come up with anything.  I think the paper is really sound aside from the grammatical and spelling errors.  Anyone else have ideas?

**Comment by aisobran** [comment]
Added two more potential improvements. I endorse submission.

**Comment by meneal** [comment]
Looks good to me.  If Joseph is good with it we should submit.

**Comment by ghost** [comment]
I'm fine with submitting.

On Tue, Oct 20, 2015 at 9:40 AM, Matthew Neal notifications@github.com
wrote:

> Looks good to me. If Joseph is good with it we should submit.
> 
> On Tue, Oct 20, 2015 at 8:46 AM, Alexander Sobran <
> notifications@github.com>
> wrote:
> 
> > Added two more potential improvements. I endorse submission.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LambdaConglomerate/x9115lam/issues/14#issuecomment-149554150
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LambdaConglomerate/x9115lam/issues/14#issuecomment-149571362
> .

## 

_Joseph Sankar (About Me) http://josephsankar.me_
Master of Computer Science, Class of 2016, North Carolina State University
Bachelor's in Computer Science, Class of 2015, North Carolina State
University

**Comment by meneal** [comment]
Submitted.
