### ISSUE TITLE
Reading 7

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#18]
I think this 2012 paper would be great:
http://dl.acm.org/citation.cfm?id=2393669

One of the problems that keep coming up in fault prediction is the lack of history for new projects and this paper addresses that issue, so called cross-project defect prediction. Let me know what you think

**Comment by meneal** [comment]
Seems perfect to me.  Here's a direct link: http://macbeth.cs.ucdavis.edu/xbugs.pdf.

**Comment by ghost** [comment]
Looks very interesting to me. Definitely looking forward to reading it.

**Comment by ghost** [comment]
In looking for connections to other papers, I browsed through the list of references. I saw two different papers that we have already summarized, but they weren't cited within the text. I guess we'll have to make broader connections, unless we can find a direct citation to a paper we've already looked at.

**Comment by aisobran** [comment]
There's a direct reference to cost-effectiveness which was from our first or second paper.

**Comment by ghost** [comment]
Ok, I found reference 23 which is for our first paper. For some reason it wasn't working when I searched it earlier. There is also reference 2 which is for our second paper but which doesn't have an in-text citation.

**Comment by aisobran** [comment]
Added Hypothesis, informative visualizations and two possible improvements. This looks ready to go.

**Comment by ghost** [comment]
I just looked at [Menzies' reading notes](https://github.com/txt/mase/blob/master/READING.md) and our sixth reading is actually to identify reusable data in papers 1-5. Please have a look to make sure I'm interpreting it correctly. I have no idea how I missed this.

If so, we can actually make this Paper 7 and work on gathering reusable data for our sixth reading assignment.

**Comment by aisobran** [comment]
Moved this over to paper 7, I think this is ready to go.

**Comment by meneal** [comment]
So I'm not sure if either of you saw the email that anything beyond reading 6 is bonus now, but that is the case.  So I'm not sure whether he intended us to continue readings beyond reading six, and if so does he intend for us to consider reading six as just looking for data.  I think we should ask a few questions in class tomorrow:
- Are we supposed to continue reading papers all the way up through paper 9 and are we even going to have the essay part of the reading assignment?
- If we aren't going ton continue reading papers, should we actually read a paper for reading six, or just look for data in readings 1-5?

One of us can just ask on the message board I suppose.  He just isn't completely clear on what he wants.

As far as what we have for Reading 6/7 I think it's perfect.  I think the only consideration is how to actually submit it from here.

**Comment by ghost** [comment]
I saw the email, but I assumed it was only for the coding assignments.
Looking back at it, you're right, it looks like he's only requiring up to
reading 6 and code 6.

In that case, I agree that we should definitely ask him about how we are
going to write our big paper since we would essentially have half the
material compared to if we would do all the reading assignments.

On Wed, Oct 28, 2015 at 8:59 PM, Matthew Neal notifications@github.com
wrote:

> So I'm not sure if either of you saw the email that anything beyond
> reading 6 is bonus now, but that is the case. So I'm not sure whether he
> intended us to continue readings beyond reading six, and if so does he
> intend for us to consider reading six as just looking for data. I think we
> should ask a few questions in class tomorrow:
> 
>    -
> 
>    Are we supposed to continue reading papers all the way up through
>    paper 9 and are we even going to have the essay part of the reading
>    assignment?
>    -
> 
>    If we aren't going ton continue reading papers, should we actually
>    read a paper for reading six, or just look for data in readings 1-5?
> 
> One of us can just ask on the message board I suppose. He just isn't
> completely clear on what he wants.
> 
> As far as what we have for Reading 6/7 I think it's perfect. I think the
> only consideration is how to actually submit it from here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LambdaConglomerate/x9115lam/issues/18#issuecomment-152043845
> .

## 

_Joseph Sankar (About Me) http://josephsankar.me_
Master of Computer Science, Class of 2016, North Carolina State University
Bachelor's in Computer Science, Class of 2015, North Carolina State
University

**Comment by ghost** [comment]
Just a note on reading 6, I made a readme file in the folder as to why we did not make a submission. Let me know if it looks okay and I'll submit it.

**Comment by ghost** [comment]
Submitted this, so closing.
