### ISSUE TITLE
Reading 8

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#19]
For the next paper I suggest we choose one of these 3:

This one just sounds awesome because of the transfer learning approach, pretty much making it possible to predict defects in brand new projects: http://dl.acm.org/citation.cfm?id=2486839

This one may be good as it summarizes much of what we read and will be useful as we write out the final paper: http://dl.acm.org/citation.cfm?id=2486846

This one seems interesting as it splits defect prediction per developer to have a defect prediction model for each developer: http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6693087&tag=1

**Comment by meneal** [comment]
I'm happy to go with any of these, but I think I favor the personalized
defect prediction per developer paper.  Seems like it would add something
completely different than the other papers we've looked at so far.  That
said, like I noted in the other thread, I'm not sure whether we even need
to do this or not.

**Comment by meneal** [comment]
Anyone have any other thoughts on this or should we go with the personalized defect prediction paper?

**Comment by ghost** [comment]
I'm fine with any of the papers as long as it makes sense for our writing our final paper.

**Comment by meneal** [comment]
I'm going to start reading the personalized defect prediction one then.

**Comment by ghost** [comment]
Cool, I'll start reading this today.

On Wed, Nov 11, 2015 at 9:47 AM, Matthew Neal notifications@github.com
wrote:

> I'm going to start reading the personalized defect prediction one then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LambdaConglomerate/x9115lam/issues/19#issuecomment-155801664
> .

## 

_Joseph Sankar (About Me) http://josephsankar.me_
Master of Computer Science, Class of 2016, North Carolina State University
Bachelor's in Computer Science, Class of 2015, North Carolina State
University

**Comment by ghost** [comment]
Here's a direct link to the paper: https://uwspace.uwaterloo.ca/bitstream/handle/10012/7786/Jiang_Tian.pdf?sequence=1

**Comment by aisobran** [comment]
Did you guys start of that paper yet? Just curious because Menzies will be talking about transfer learning in class and I think it would be cool to read the first paper. I will either way, just let me know.

**Comment by meneal** [comment]
I've already read that other paper.  I'll post a write up or part of one
tonight.

**Comment by meneal** [comment]
I just pushed the writeup for this.  Most everything is up there.  It's missing 2 blocks for feature extraction and one keyword.  Change anything or post if you disagree with anything I put up there.

**Comment by ghost** [comment]
Just pushed some more stuff, so now it should be pretty much ready for submission. One thing I was a bit confused about was on the second page it states that Tian Jiang is the only author, but the citation has three authors listed. Because the paper explicitly states it, I tried to change the wording to "author" instead of "authors" but I could have missed something. Have a look, and let me know what you think.

**Comment by meneal** [comment]
Honestly it doesn't really matter a whole lot since we don't actually need
to submit this thing.  I just figured we'd do this so that we could have
these for reference when it comes time for the final paper.  Do we get
extra credit though if we do submit?

**Comment by ghost** [comment]
I don't think so, since it looks like Menzies is expecting us to do these anyways. But it's something we can ask him tomorrow.

**Comment by aisobran** [comment]
I think we should submit, it shouldn't hurt.

**Comment by ghost** [comment]
Since other groups have already submitted and received credit for these readings, I went ahead and submitted.
