### ISSUE TITLE
Paper 1 Selection

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#2]
These are the four that fit the bill for what we need:
- [Automated web application testing using search based software engineering](https://scholar.google.com/scholar?oi=bibs&cluster=7723102817598141683&btnI=1&hl=en) - 53 Citations
- [Ecological inference in empirical software engineering](https://scholar.google.com/scholar?oi=bibs&cluster=6994049198280130435&btnI=1&hl=en) - 51 Citations
- [Detection of feature interactions using feature-aware verification](https://scholar.google.com/scholar?oi=bibs&cluster=13295047810992639072&btnI=1&hl=en) - 66 Citations
- [Towards more accurate retrieval of duplicate bug reports](https://scholar.google.com/scholar?oi=bibs&cluster=14419406738375928035&btnI=1&hl=en) - 71 Citations

Vote for your favorite.

**Comment by aisobran** [comment]
Lets also try to pick a recursive history path for each. I thought we eventually decided to avoid the bug reports paper.

**Comment by meneal** [comment]
You're right.  My memory isn't what it used to be.  We can leave that one
out.

On Wed, Aug 26, 2015 at 10:36 AM, Alexander Sobran <notifications@github.com

**Comment by ghost** [comment]
Here the paths that look promising in order of my preference:
1. Automated web application testing using search based software engineering
   Finding Bugs in Web Applications Using Dynamic Test Generation and Explicit-State Model Checking, 2010
   Automatic creation of SQL Injection and cross-site scripting attacks, 2009
   Finding bugs in dynamic web applications, 2008
2. Ecological inference in empirical software engineering
   Defect prediction from static code features: current results, limitations, new approaches, 2010
   Practical considerations in deploying AI for defect prediction: a case study within the Turkish telecommunication industry, 2009
   The influence of organizational structure on software quality: an empirical case study, 2008
3. Detection of feature interactions using feature-aware verification
   Type safety for feature-oriented product lines, 2010
   FEATUREHOUSE: Language-independent, automated software composition, 2009
   Superimposition: a language-independent approach to software composition, 2008

I'm fine with either 1 or 2, but 3 just seems uninteresting to me. What do you all think?

**Comment by aisobran** [comment]
I like 2. But I'd rather do this for the 2010 paper

A systematic and comprehensive investigation of methods to build and evaluate fault prediction models, 2010

But it doesn't have any 2009 references, so maybe we can use the same 2009, 2008 papers as above.

I think 3 is a little more interesting if we branch at:

An algebraic foundation for automatic feature-based program synthesis, 2010
Same 2009 and 2008 paper as above.

I'm not a big fan of 1 or testing. I'd rather build a modeling skill set applied to a different domain of automated SE.

**Comment by meneal** [comment]
How about this then as a path:
- [Ecological inference in empirical software engineering](https://scholar.google.com/scholar?oi=bibs&cluster=6994049198280130435&btnI=1&hl=en) 2011
- [A systematic and comprehensive investigation of methods to build and evaluate fault prediction models](http://dl.acm.org/citation.cfm?id=1663909&CFID=540207580&CFTOKEN=13537993) 2010
- [Mining software repositories for comprehensible software fault prediction models](http://dl.acm.org/citation.cfm?id=1353064&CFID=540207580&CFTOKEN=13537993) 2008

I'm not sure if you heard this Joseph, but Dr. Menzies said it was ok to use any older reference as well.  I figure we get through these 3 and then pick a path going forward.  Do either of you have other preferences?

**Comment by meneal** [comment]
Seems like we're happy with this list.  Closing.
