### ISSUE TITLE
Convergence

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#21]
So this one is sort of a question mark at this point.  Not totally sure whether we're going to actually need to do this or not, but it should be reasonably straightforward to add this in if we need it.  If you want to take a look at how it's done, you can see it in these places:
- [Here](http://www.iitk.ac.in/kangal/Deb_NSGA-II.pdf) in section B under performance measures.  Pretty interesting paper anyway if you want to check it out.
- [here](https://github.com/ai-se/storm/blob/master/PerformanceMetrics/IGD/IGD_Calculation.py) in Menzies' group's storm project.

If we do add this in, one question is really where to put it.  We can put it into the end of the run shell script and run it with the hypervolume/spread, or we can just have it run in the state at the end of a run.  There's a stub for it on line 114 of state.py.

**Comment by ghost** [comment]
I pushed a script for convergence. It looks in the obtained PFs folder and for each file finds the matching true PF file and calculates the convergence for each. Right now it just prints out the list of values for each model, but I can make it create an output file instead with the values. 

I'm wondering if I should append to this file in case we do multiple runs of the same model or if we should just overwrite the file each time.

**Comment by meneal** [comment]
Not totally sure yet about the file.  Are you printing out the name of the
optimizer and the model along with the convergence figure?  Thinking about
it a bit it might be best if it output to a file and just appended each
time.  Maybe with a timestamp?

**Comment by ghost** [comment]
Not right now, just the number. So you want the model name, the number, and the timestamp in one output file?

**Comment by meneal** [comment]
Yeah in one output file.  Don't worry about the timestamp.  I thought about
it and that probably doesn't make sense.  We'll probably end up purging the
output file from time to time.

**Comment by ghost** [comment]
I ran test.py but it doesn't look like it's writing to the obtained PF file. I see that it creates the file but it's empty. Any reason why that may be happening?

**Comment by meneal** [comment]
It's because there's nothing currently being written to the frontier in the
state.  I'm working on that right now actually.  I've run into some
weirdness with retries, for some reason I'm getting a crash if I run more
than 1 retry.

**Comment by ghost** [comment]
I pushed the changes requested. Running convergence.py now outputs to a file. Each line in the file corresponds to an obtained PF and includes the model name and the convergence value. Right now the file is overwritten every time the script is run.

Let me know if you see any issues or want to make changes.

**Comment by meneal** [comment]
Something weird.  I pulled this and tried running it with some obtained fronts and I'm not getting any change to convergence.txt.  Any idea why that might happen?

**Comment by ghost** [comment]
Hmmm, I ran it again with different models and the file updated. I noticed that all the output was all on one line though, so I just pushed a fix for that.

Maybe you have a write lock on the file? Try deleting the file and running the script again.

**Comment by meneal** [comment]
I just ran it again after deleting the txt file and nothing happens...  What file is it supposed to be working on?  Does it just use whatever is in Spread?

DESKTOP-CN1FQA2:Convergence meneal$ python convergence.py
DESKTOP-CN1FQA2:Convergence meneal$ ls
convergence.py

**Comment by meneal** [comment]
damnit!  It's a Windoze issue.  This line 
`convergence_file = open(".\convergence.txt", 'w')`
creates a dotfile on OSX or linux.
DESKTOP-CN1FQA2:Convergence meneal$ ls -la
total 16
drwxr-xr-x  4 meneal  staff   136 Dec  5 13:56 .
drwxr-xr-x  7 meneal  staff   238 Nov 29 17:38 ..
-rw-r--r--  1 meneal  staff    19 Dec  5 13:56 .\convergence.txt
-rw-r--r--  1 meneal  staff  2198 Dec  5 13:52 convergence.py

Do you need that ".\" for this to work on your machine?  I would think that it would work without that.

**Comment by ghost** [comment]
I'll try when I get home later. I'm thinking it should work though.

**Comment by ghost** [comment]
Removing the "./" works on my machine, so I pushed the changes. Let me know if it works.
