### ISSUE TITLE
Review of AdaptiveGlobalPSO

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#24]
This is where we've really focused our work up until this point.  Setting up one rig that actually runs PSO correctly and creates a reasonable frontier.  I think that adaptiveGlobalPSO is doing this now for all of the models.  Some it's going to run slower than others.  

The main thing at this point is that I need some sort of sanity check to make sure that this is actually working correctly.  Once we know that adaptive is right we can easily manipulate the other optimizers to do the same thing, since in most cases the only real change is in the calculation of velocity.

**Comment by ghost** [comment]
I think energy could serve as a sanity check since we're only doing 3 objectives.

**Comment by meneal** [comment]
This is complete.
