### ISSUE TITLE
Splitting Up Code 2

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#3]
Any ideas how best to go about this?

**Comment by aisobran** [comment]
All of exercise from chapter 3 go in think3.py and all of the exercises from chapter 4 go into think4.py.

**Comment by meneal** [comment]
I meant how should we split up the work.  Sorry that wasn't clear.

**Comment by meneal** [comment]
I'm working on 4.2 right now.

**Comment by meneal** [comment]
I pushed some stuff on 4 a minute ago.  Almost draws one of the flowers.  I'm still trying to do it without looking at the solution.

**Comment by ghost** [comment]
It doesn't look like swampy is installed in our repo. I'm trying to run think4.py in Cloud9 and I'm getting `ImportError: No module named swampy.TurtleWorld`.

**Comment by ghost** [comment]
I can finish the chapter 3 exercises.

**Comment by meneal** [comment]
You have to install swampy on your machine.  It isn't actually attached to
the project. On OS X Tkinter is preinstalled. I think you have to install
swampy via pip wherever you are working.

**Comment by ghost** [comment]
I installed swampy on my machine and the program works. I was just wondering whether we need to have the swampy libs on our repo so someone who clones/forks our work doesn't need to install swampy themselves.

**Comment by meneal** [comment]
Anyone who uses the repo will need to install swampy themselves.  It's
pretty common to require specific modules be installed prior to using code
from a repo.  We'd just want to put that as a prerequisite in our Readme.
There may be some sort of way to list all of the needed dependencies for a
project that are available from pip and have pip just install all of them,
but I'm not sure about that.

**Comment by meneal** [comment]
I think at this point we're done with Exercise 4.2 and 4.3.  Let me know if you if you see any problems or if you think we are ready to roll for submission.

**Comment by ghost** [comment]
Exercises 4.2 and 4.3 look good to me. If you think the 3.x exercises look good, feel free to submit.

**Comment by meneal** [comment]
Something wasn't quite right with exercise 3, but I fixed it.  For some
reason it output tabs instead of spaces.  Weird stuff.  I'm submitting it
now.
