### ISSUE TITLE
Grapher

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#32]
I got grapher working with this setup and it now handles multiple situations(decisions, objectives). It takes in the frontier at each retry and adds it to the plot. Each retry is different color. Instead of a graph popping up it now writes it straight to the pics folder, I think that will make life easier.

It may also be useful to make a graph of the particles behaviors at each retry. That's a ton of graphs but at least it's useful for seeing how our heuristics affect behavior. This will also be written into it's own folder so we assess it after the run.

I tried to push the changes but there are conflicts. I'll resolve the conflicts tomorrow and push everything up when I'm fresh.

**Comment by meneal** [comment]
One thing we may want to make sure about is the size of the repo.  If we push all of the graphs we could start to hit that limit pretty quickly.  Not exactly sure how to get around it either.  Def something to think about.

There's some limit to the total size the repo can be.  Did you already add back the min max stuff referenced in the other issue?

**Comment by aisobran** [comment]
Pushed up the new grapher, it graphs the frontiers from adaptive. There are some example graphs under pics with only 4 retries. I'm doing a big run right  now with 50 retries for each model and will push the results when done.

**Comment by aisobran** [comment]
Also adding in the optimal frontiers.

**Comment by aisobran** [comment]
There's another bug in graphing 3d objectives. Fixing it now.

**Comment by aisobran** [comment]
Pushed the fixes. And an initial coding of adding the PFs. Having some issues with some of the txt files for example:

```
TypeError: Cannot cast array data from dtype('float64') to dtype('S32') according to the rule 'safe'
```

I'm looking into it.

**Comment by aisobran** [comment]
You can see the Osyczka2 pics worked. The true PF is black and our frontier is aqua. Looks pretty poor but let me fix this then see how the other models come out.

Also, only did 3 retries for brevity.

**Comment by aisobran** [comment]
Pushed the fix, it was a typing issue with the 3d plots. Running a 10 retry run on all models to get some base pics. 

I pushed a single retry run of DTLZ1 under pics. This also looks poor but lets see how the results pan out.

I think I will also do a run plotting all the vectors encountered in a run to make sure we're not picking worse vectors.

**Comment by aisobran** [comment]
The frontiers look way off for DTLZ1.

**Comment by meneal** [comment]
Definitely.  It's just like I was saying the other day.  We're really far
off.  I don't know why though.  It's likely because we're just not running
anywhere near long enough to get there though.  Not only that with only one
retry we're only going to end up with one frontier value for DTLZ1 as far
as I have seen.

**Comment by aisobran** [comment]
Just pushed up some 10 retry graphs. They all look really poor. Still need to do tanaka, viennets, and srinivas. Will be up shortly.

**Comment by aisobran** [comment]
ConstrEx has points that a better than the true PF. It had a bug, fixed it.

**Comment by aisobran** [comment]
Added a particle history functionality to grapher. It looks like this 
![dtlz1trackedparticleobjectives](https://cloud.githubusercontent.com/assets/8948489/11608390/906338ee-9b35-11e5-8114-c0368615b9e6.png)

![fonsecatrackedparticleobjectives](https://cloud.githubusercontent.com/assets/8948489/11608397/97be3d82-9b35-11e5-8897-d78df8b185eb.png)

Where the greater the opacity the later in the timeline the point it.

**Comment by meneal** [comment]
Do you think this gives us any insight into what's happening?  I'm just not
sure.

**Comment by meneal** [comment]
I think that it helps to some degree to see where the particles are in terms of objectives. but do you think it gives any sense of what to do about why we're not getting to the frontier on DTLZ?
