### ISSUE TITLE
Reference List

### ISSUE THREAD

**Issue by meneal** [LambdaConglomerate/x9115lam#33]
Just starting a list of references that may either be useful or we have used in the paper so far:
- [This](http://www.tik.ee.ethz.ch/sop/pisa/publications/KTZ2005a.pdf) is an interesting one on Performance Assessment from Zitler.
- [The Deb/Zitler Paper with DTLZ](http://www.tik.ee.ethz.ch/sop/publicationListFiles/dtlz2002a.pdf) lists you everything about DTLZ. The other [Deb Zitler paper](http://www.tik.ee.ethz.ch/file/c7c5e610a0c7e26d566a3601e5cce2f4/DTLZ2001a.pdf).  The first paper is from 2002 and the second is from 2001.
- [Deb paper on NSGA II](http://www.iitk.ac.in/kangal/Deb_NSGA-II.pdf)

**Comment by ghost** [comment]
I made a [wiki page](https://github.com/LambdaConglomerate/x9115lam/wiki/Project-Reference-Papers) that lists the references for our project. I think it'll be easier to update that instead of editing this issue. But if you feel differently, we can add the papers listed there to your first post.

**Comment by aisobran** [comment]
I endorse the wiki page

**Comment by meneal** [comment]
Good stuff.

**Comment by meneal** [comment]
Closing.  We're doing this in the wiki now.
