### ISSUE TITLE
front_test.py

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#36]
Does this serve any purpose or was it in there for just testing/debugging?

**Comment by meneal** [comment]
Testing debugging.  The reason I had it in there was to check and see
whether cdom worked correctly with non-normalized values or not.  Looks
like I didn't try big enough values!

**Comment by aisobran** [comment]
Cool if I remove it?

**Comment by meneal** [comment]
Yeah should be ok.
