### ISSUE TITLE
Constriction Factor

### ISSUE THREAD

**Issue by aisobran** [LambdaConglomerate/x9115lam#39]
I've been trying to determine why we have so many deaths and evaluated the k calculation. It's always 1.0 which pretty much makes it useless and turns it into classical PSO without a Vmax which would explain why we have so many deaths.

**Comment by meneal** [comment]
oh no!  No wonder why it's not working.  Shit.  I'm glad you found that!

**Comment by aisobran** [comment]
Getting rid of the leading term in the denominator helps. Makes it 0.5. I think we want the constriction factor to be 0 < X < 1. We might just want to hard code it in too, if we're not going to play around with either phi

**Comment by aisobran** [comment]
0.25 gave this type of behaviour (500 steps)
<img width="708" alt="screen shot 2015-12-06 at 11 51 21 am" src="https://cloud.githubusercontent.com/assets/8948489/11614401/f4b7efee-9c0f-11e5-82ec-54150dea4785.png">

<img width="678" alt="screen shot 2015-12-06 at 11 51 46 am" src="https://cloud.githubusercontent.com/assets/8948489/11614402/f8755130-9c0f-11e5-86ff-b9bc9d5f4e79.png">

<img width="687" alt="screen shot 2015-12-06 at 11 51 53 am" src="https://cloud.githubusercontent.com/assets/8948489/11614403/fcb87218-9c0f-11e5-93d4-6f5874bc8eb5.png">

**Comment by aisobran** [comment]
That looks like the type of behavior we are looking for.

**Comment by meneal** [comment]
"K" is the construction factor:
K = 2 / ( abs(2 - φ - sqrt(φ \* φ) - 4φ))
φ = φ1 + φ2
φ > 4.
This is what menzies posted on his lecture.  

phi_tot = phi_1 + phi_2
k = (2.0/math.fabs(2.0 - (phi_tot) - math.sqrt(phi_tot*_2.0 - 4.0_phi_tot)))

Does that look the same?

**Comment by aisobran** [comment]
Thats phi_total > 4, we have phi_total = 4.

**Comment by meneal** [comment]
damnit all.  That's the difference.

**Comment by meneal** [comment]
If you even increase beyond 4 do we end up with similar behavior to what you were showing above through pegging the value of k?

**Comment by aisobran** [comment]
Yeah and it's a huge difference because the constriction factor with exponentially reduce the previous velocities.  

Setting it to 0.25 gave some really good results for DTLZ1. Closest ever.

<img width="690" alt="screen shot 2015-12-06 at 11 57 06 am" src="https://cloud.githubusercontent.com/assets/8948489/11614435/a77c166e-9c10-11e5-9163-62e5bbebf58e.png">

<img width="691" alt="screen shot 2015-12-06 at 11 57 12 am" src="https://cloud.githubusercontent.com/assets/8948489/11614438/badc41b6-9c10-11e5-8032-586a0a9e1054.png">

**Comment by meneal** [comment]
Damn I have to say I'm super happy that worked.  I feel like a dick for messing it up though.

**Comment by aisobran** [comment]
Increasing the phi gives the the same type of affect if it's high enough. Changes the learning behavior though.
