### ISSUE TITLE
Metrics Parser

### ISSUE THREAD

**Issue by ghost** [LambdaConglomerate/x9115lam#41]
Just pushed a metrics parser script `metrics/analyzer/metricparser.py`. When you run it, it reads all the files in `metrics/out/` and creates a csv version of them to import into Excel/Google Sheets.

**Comment by aisobran** [comment]
Usually csvs are not put together like this unless this is some excel format. The columns should be model, hypervolume, spread, convergence

**Comment by ghost** [comment]
I was able to import the csvs into Google Sheets and make a [chart](https://docs.google.com/a/ncsu.edu/spreadsheets/d/1_7VOAc0098-J2H_IheW93Oeky8rOyBN74av2a3b5uD4/edit?usp=sharing). What's the advantage to having everything in columns?

**Comment by aisobran** [comment]
Generally csvs are in the format I reordered to in the updated google sheet. This makes it easier to import into python using pandas or into R. If this is how you want to handle the data though I don't see a problem with it. But we will have to create graphs by hand instead of scripting it.

**Comment by ghost** [comment]
I pushed a fix for the parser that outputs in the format you suggested.
