### ISSUE TITLE
Reading Part 1: Paper 1

### ISSUE THREAD

**Issue by ghost** [LambdaConglomerate/x9115lam#5]
I think it would be a good idea to plan our work for each reading assignment. We have already decided our first paper will be [Ecological inference in empirical software engineering](http://dl.acm.org/citation.cfm?id=2190191). 

We need to have the following for the first paper, according to [Dr. Menzies' instructions](https://github.com/txt/mase/blob/master/READING.md):
1. A clear reference.
2. Four important keywords with definitions.
3. Four brief notes on feature extraction items 1-19.
4. Three ways the paper could be improved.

I'm thinking we should really split up 2-4, and the first person to push should also do 1 since it should be trivial.

Anyone have any preferences?

**Comment by ghost** [comment]
I just pushed a TeX file containing an outline of what we'll need. I went ahead and tried to do the reference based on Menzies' example, but please look over it. I'm not sure if we should be using a format like MLA or if we should just stick to his example.

Matthew suggested that we each try to do 2-4 on our own and choose the best of them. My only concern is what should we do when all of us have good parts, how do we choose what to select for our submission?

**Comment by meneal** [comment]
What I really meant is that what we turn in can be a combination of all of
our work.  The major benefit there is that we'll all need to read the
papers.  If we don't all read all of the papers then we're really not
getting the benefit of the assignment overall.  Also, I just finished the
first one and wrote something up, and I feel like it helped me a fair
amount to understand the material better to go through the writeup.

As far as format I'd assume that we don't need to go to the trouble of
LaTex for the weekly reading stuff.  I'd think that he only will want that
for the final paper.  Probably markdown will be good enough.  I think
that's how I'll write mine to start.  We can ask in class tomorrow though.

**Comment by meneal** [comment]
Actually, looking at a few other people's repos it looks like everyone is using LaTex.  So I suppose we should too.  No problem there though.

**Comment by meneal** [comment]
I'm thinking we should have directories in the reading directory for each paper we look at  and not keep the stuff for readings in the paper directory.  I'm going to do that for now.  Let me know if you disagree and I'll move this stuff back.

**Comment by ghost** [comment]
Oh, is that what hw/read is for? If so, then that makes more sense.

**Comment by aisobran** [comment]
I don't agree with the motivational statement written. It seems more like a set of definitions and a conclusion. This:

"Therefore, it would be useful to draw conclusions from higher
levels that would apply to lower levels."

Is a a direct conclusion and not a motivational statement. The motivation for this paper is more along the lines of applying ecological inference to empirical SE to further the goal of determining at which scale it is appropriate to:

1) Apply predictive machine learning.
2) Hypothesis testing.

And how translatable/valid those applications/generated models, formed at one scale, are to different scales.

**Comment by meneal** [comment]
That's pretty close to what I came up with for motivation as well.

Honestly I've been thinking about this a bit more and I think it might be easiest to meet and discuss the paper, and make up our summary.  Let's talk about it at class today and maybe come up with a time to meet on Thursday.

**Comment by meneal** [comment]
I just added a number of things into read/1  Some of it might not be that great.  Please take a look and pull anything you disagree with.  I changed the description formatting to itemize for the feature extraction section.  I also added a few other keywords.  We can just keep whatever everyone wants for that.  I did add a little blurb about typos for the needs improvement section.  I changed the motivation feature extraction to something more like what we discussed.  Can and should be changed if not what we want.

**Comment by aisobran** [comment]
Am I the only one that doesn't see the paper in read/1?

The git history says everything was deleted and nothing was added.

**Comment by meneal** [comment]
Sorry about that!!  Somehow the folder wasn't being picked up by git on calling `git status`.  It's up there now.

**Comment by ghost** [comment]
Just pushed a change to the summary. Let me know what you think and if you're ready to submit.

**Comment by aisobran** [comment]
I combined the the two motivational statements into 1 and added to the new results, addressing their ultimate conclusions of aggregated models evaluating better than they are and the loss of inference from aggregated models when applied to dis-aggregated components. 

I also had another issue with how they defined LS, GS. Their initial definition for both are synonymous just worded differently. It's easy to infer what is meant later. I didn't include this in the improvements because we're at 1000 words. It's just something to think about.

I'm ready to submit.

**Comment by ghost** [comment]
I just submitted this. Closing for now.
