### ISSUE TITLE
Code 3

### ISSUE THREAD

**Issue by ghost** [LambdaConglomerate/x9115lam#6]
Let's talk about how we are going to split Code3. It looks like Sasha is working on 10.15 Exercise 8, so I will start working on the Employee class.

**Comment by ghost** [comment]
I just pushed the Employee class. Have a look and let me know how it looks.

It looks like poker will be a big one. It looks like we can divide the task according to 3-6 in 18.12 Exercise 6. Since Employee was relatively easy, I'm fine with starting poker. Let me know if you have any objections to this.

**Comment by ghost** [comment]
I just pushed the checks for poker hand methods. If anyone wants to work on the classify method, let me know. Otherwise, I'll start working on it tomorrow night.

**Comment by meneal** [comment]
I definitely want to work on some of this.  I probably can't get working on
it until Friday night or Sunday.  Make sure to leave me with something to
do.  I don't really care how hard it is.  I just haven't had a chance to
get a good look at it yet.  Will definitely look at the paper too and
submit on Friday/Sunday.

**Comment by aisobran** [comment]
10.8 is done and the pic is added.

**Comment by meneal** [comment]
I'm working on classify now.

**Comment by meneal** [comment]
I think we need some tests for this.  Would you knock that out Sasha?  :)

**Comment by meneal** [comment]
I think poker hands is pretty much complete now.  Running a test with 10 million decks on AWS just to see if I can get it to output the same probabilities as on Wikipedia.  I'll post the output whenever the test finishes.

**Comment by meneal** [comment]
Output is posted in the README.  I think this is done but somebody else should check over it and either submit or state what else needs to be done.

**Comment by ghost** [comment]
I ran the numbers on my machine and they are very similar to yours and to the ones on Wikipedia. I am okay with submitting if Sasha approves.

**Comment by aisobran** [comment]
Good to go.

**Comment by meneal** [comment]
Make sure if you close to put in the tiny url for the submission.  I just
put this one in.
